name: pokedeck
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_tts: ^4.2.3
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon-pokedeck.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icon-pokedeck.png"
  min_sdk_android: 21 # android min sdk min:16, default 21